### ISSUE TITLE
Single `just` package

### ISSUE THREAD

**Issue by nolde** [angus-c/just#179]
Would you be willing to make a single package, `just`, that contains all functions?

It would be nice to have only one dependency in my `package.json`, and then be able to required as needed, like `import omit from 'just/omit'`. I already use bundlers that avoid code that is not necessary, so having the extra files would not matter that much.

Is that something you would be willing to do, or does it goes against your objectives?

**Comment by angus-c** [comment]
Not a bad idea. Only question I can see is whether to abstract common code (as Lodash modular does). I'd lean towards not abstracting for the sake of not maintaining additional code, and also because this will actually keep bundle size down when importing sub-modules (Lodash modular imports are inevitably larger because they depend on shared code, not all of which is essential for each import)

**Comment by nolde** [comment]
Ideally, abstracting common code would be good, but I agree that it is a lot of extra work. And `just` is already quite small as it is, so this is more of a "let's keep `package.json` small" thing than "let's get `just` even smaller".

Just a common bundle is good enough, IMHO.

**Comment by angus-c** [comment]
Hi @nolde. Does [this repo](https://github.com/jay-es/just-all) fulfill the requirement?

**Comment by nolde** [comment]
Yeah, it is almost there, but not quite! It has all function requires within a single file, so if you don't have tree shaking, you're adding all functions, even if you don't use them.

Thanks for warning me, though!
I might end up doing one myself, sometime.

I'll close this issue.

**Comment by angus-c** [comment]
Thanks! (Yeah was assuming tree shaking)

**Comment by MarcusCemes** [comment]
I heard about this on the Syntax podcast, I love the simplicity and power this seems to bring, I've never really used Lodash or Underscore, this seems like a nice and lightweight toolkit.

I don't think I can wrap my head around the fact that each function has to be imported as a different npm package. If it's to "only add what you need", I understand, but tree-shaking solves this for the browser, and if tree-shaking is not available, a network request for 200 bytes is a huge waste of resources, it might actually be better to pull in one several-KB file, compression is efficient in larger files. "No dependencies" has turned into "a large number of flat dependencies".

> Hi @nolde. Does [this repo](https://github.com/jay-es/just-all) fulfill the requirement?

Not exactly, it re-exports every single npm package from a single file, it's a lot of disk operations and exports, we're back to a large number of dependencies problem.  That is a _lot_ of **synchronous** `require` calls, this is a problem for Node.js, as Webpack and friends will convert `require` calls to its own intra-script module resolution, whereas Node.js usually has to hit the disk.

> so if you don't have tree shaking, you're adding all functions, even if you don't use them.

Why is this a problem? Yes, you might pull in some things you don't need, but I think the signature of this library is still _really_ small. Splitting into individual files/packages works, but after a certain point, you get diminishing returns. Even if everything was compacted into a single file, I think the total size would be still very small compared to other dependencies. Whether it's Webpack or Node.js module loader, there is some overhead to each loaded module, I would be interested to know whether there are actually any speed/memory savings by separating out into packages when using several helpers.

This is what I believe:

- **Browser w/o tree-shaking**: requires multiple wasteful network requests
- **Browser w/ tree-shaking**: possibly slightly less space-efficient than a single file due to the number of separate modules and a large number of dependencies
- **Node.js**: each `require` call is expensive, more so than parsing the file and loading it into memory, tree-shaking is a possibility (perhaps more so now with ESBuild), but rare

In my opinion, ES modules would work great with this.

> In ESM, the module loader runs in asynchronous phases. In the first phase, it parses the script to detect calls to import and export without running the imported script. 

[Source](https://redfin.engineering/node-modules-at-war-why-commonjs-and-es-modules-cant-get-along-9617135eeca1)

When you import a particular item using the ES syntax, the loader will find the exported member, and only parse that part of the script and any code it depends on. Try it, add some top-level side-effect code, like a `console.log`, it won't run.

[Browser support for ESM](https://caniuse.com/es6-module) is really good nowadays, most frontend build tools will probably still convert it to CJS for compatibility reasons but will tree-shake when bundling anyway, so no loss there. Without tree-shaking, yes. There will be a larger resource to download. How many people will actually be affected by this, and is it still non-negligible next to stylesheet and image assets? ESM is now stable for Node.js also, a single disk IO operation (well, a _single_ multiple of how many ops are needed to locate and load an npm package), and only parsing and loading exactly what needs to be loaded, not the whole file. Win-win, no?

Regardless, thank you for the excellent work you have done here, I don't mean to criticise but to suggest a possible way forward. I will definitely be following this project's progress in the future!
