### ISSUE TITLE
Use ES Modules with type:module

### ISSUE THREAD

**Issue by fregante** [angus-c/just#192]
It'd be great to have `just` be a Node-compatible ES Module with `type: "module"` in the package.json

I don't remember if there's a backwards-compatible way to have both CJS and `type:module` in the same import, but this is definitely possible:

```
- index.js // cjs file
- esm/index.js // esm file
- esm/package.json // Content: `{"type": "module"}`
```

This would enable both:

```js
const something = require('just-something');
```

```js
import something from 'just-something/esm'; // Notice the `/esm`
```

**Comment by angus-c** [comment]
yes I should look into this, thanks

**Comment by boogerlad** [comment]
any update on this?

**Comment by angus-c** [comment]
Sorry I haven't had the time to get to this. In theory it should be fairly simple (if repetitive) but I wanted to take the time to verify a POC before making updates. Will try to look at this over the holidays.

**Comment by antony** [comment]
one option which can save time with this is to add a small 3-4 line rollup file which compiles an es6 version of the library into `dist` which can just be done at packaging time.

There's an example of this here: https://github.com/mcollina/fastq/pull/48

**Comment by raulfdm** [comment]
@angus-c want some help on this task?

**Comment by angus-c** [comment]
> @angus-c want some help on this task?

sure!

**Comment by PCOffline** [comment]
Hey, any updates with this?

**Comment by raulfdm** [comment]
@angus-c I was about start but I think, before any work, we should discuss how we want to do that.

I believe there are some strategies to make it work.

## Copy strategy

If we don't want to change anything, we could simply:

1. make a `index.js` copy and name `index.esm.js`
2. replace the `module.exports` with `export default`
2. Add the property `type: module` to inform that ESM should take precedence if supported;
3. Point the `index.esm.js` file as `module` (`"module": "index.esm.js`)

The problem with that is we'll end up having duplicated code. If something needs to be fixed, it'll need to be done in 2 places.

## Single source of truth

Since every package is self contained and written in CJS way, we could use a transpiler tool like SWC, ESbuild, or Rollup and then:

1. write a script to transform `index.js` into `index.esm.js` targeting `esm`;
2. Add in the package.json the `module` and `type`;
3. include that new file to published

Since you're using a monorepo, it won't be much work. The only thing we should be aware is to run the build process for every new publish.


---

I only can see these 2 approaches, let me know what you want to do so I can help in a more assertive way.

Cheers.
