### ISSUE TITLE
Typings needed

### ISSUE THREAD

**Issue by parthshah1991** [angus-c/just#20]
Would you be giving typings for these modules any time soon ?

**Comment by angus-c** [comment]
Can you be more specific? Do you mean logic to check the incoming arguments, or using something like typescript or flow? Or do you mean something else?

**Comment by parthshah1991** [comment]
I am using typescript with angular 2. So I did import the module, but it requires 'typings' for the same. 
Hence was asking, whether you'll be supporting it. 

It is a type description of all the methods. Can check lodash, node for reference.

**Comment by mightyiam** [comment]
Yup. TypeScript types. Would like them, as well. I am looking for an alternative to `lodash.keyBy`, exactly because its typings seem unsatisfactory to me. `just-index` seems like what I'm looking for, but it has no typings.

I think the easiest and most fail-safe way to have typings is to rewrite in TypeScript. But that is radical and if the developer is fond of TypeScript he would have done it by now, probably.

**Comment by angus-c** [comment]
Would adding Just here be a workaround? https://github.com/DefinitelyTyped/DefinitelyTyped

**Comment by mightyiam** [comment]
Yup. It would. I never did that, but I imagine it to be quite meticulous and error prone. I seriously don't know how types are manually made for codes as complex lodash, for example. But they are. I bet there are some tips and tricks that come with experience. Seems a bit overwhelming to me. That's why I would suggest converting to TypeScript and letting the compiler produce correct typings for the project.

**Comment by angus-c** [comment]
I would consider a TypeScript rewrite if I was already transpiling. One of the biggest benefits of writing Just in ES5 (and without dependencies) is I don't need a transpiler. This is invaluable in terms of import cost, debuggability  and predictability.

**Comment by mightyiam** [comment]
No kind of pressure from me at all here, @angus-c. Just sharing that from my experience with TypeScript, it contributes to predictability.

Debugging involves source maps, if you wish. But you could always turn them off and debug the end product. Since you're not interested in down-transpilation from new to old ES, then the end product is pretty much the source minus the types.

**Comment by angus-c** [comment]
Yeah I get that (and have used source maps a lot in other projects. I love ES2015+, it's just liberating not to use it in the case of this project since it gives me much more control over performance and size, versus deferring to babel) and I do agree that TS doesn't add transpile bloat, unlike babel/webpack.

One further consideration, I've added a lot of manual type checks for arguments which I would have to keep in *addition* to TS annotations since many won't be using Just in TS apps.
