### ISSUE TITLE
Throttle: support both leading and trailing call at the same time

### ISSUE THREAD

**Issue by Hypnosphi** [angus-c/just#207]
Right now there's `callFirst` which only allows to switch between those two modes

**Comment by angus-c** [comment]
Fixed in just-throttle@2.0
There are now `leading` and `trailing` options:

```
const fn1 = throttle(() => console.log('hello'), 500, {leading: true});
setInterval(fn1, 400);
```

If `leading` and `trailing` are both true the only `leading` is considered as true.
Initially I allowed both `leading` and `trailing` to be true but it feels unintuitive to make two invocations for a single call. The final decision is also consistent with Lodash's implementation (despite what their docs say)

**Comment by WofWca** [comment]
I suggest to reopen this, because I believe it behaves in an unexpected way. I believe "throttle" (with `{ leading: true, trailing: true }`) ensures that:
1. The underlying function is invoked at most once per n milliseconds.
2. If the wrapper is being continuously called, then the underlying function is invoked once every n milliseconds
3. For each call of the wrapper function, there must be one invocation of the underlying one at most n milliseconds later.

There is a problem with the third point.

> but it feels unintuitive to make two invocations for a single call

There is no need to make two invocations for a single call, this only happens if you call the wrapper function more than once, as per Lodash docs:

> Note: If leading and trailing options are true, func is invoked on the trailing edge of the timeout _only if the throttled function is invoked more than once_ during the wait timeout.

> The final decision is also consistent with Lodash's implementation (despite what their docs say)

Are you saying that `just-throttle` behaves the same as `_.throttle`? Based on my tests, it's not true. Go to https://lodash.com/docs/4.17.15#throttle and paste this in the console:

<details>
<summary>Code</summary>

```javascript
// Copy-pasted from the source code.
function justThrottle(fn, interval, options) {
  var timeoutId = null;
  var throttledFn = null;
  var leading = (options && options.leading);
  var trailing = (options && options.trailing);

  if (leading == null) {
    leading = true; // default
  }

  if (trailing == null) {
    trailing = !leading; //default
  }

  if (leading == true) {
    trailing = false; // forced because there should be invocation per call
  }

  var cancel = function() {
    if (timeoutId) {
      clearTimeout(timeoutId);
      timeoutId = null;
    }
  };

  var flush = function() {
    var call = throttledFn;
    cancel();

    if (call) {
      call();
    }
  };

  var throttleWrapper = function() {
    var callNow = leading && !timeoutId;
    var context = this;
    var args = arguments;

    throttledFn = function() {
      return fn.apply(context, args);
    };

    if (!timeoutId) {
      timeoutId = setTimeout(function() {
        timeoutId = null;

        if (trailing) {
          return throttledFn();
        }
      }, interval);
    }

    if (callNow) {
      callNow = false;
      return throttledFn();
    }
  };

  throttleWrapper.cancel = cancel;
  throttleWrapper.flush = flush;

  return throttleWrapper;
}

lodashThrottled = _.throttle(() => console.log('lodash'), 1000);
justThrottled = justThrottle(() => console.log('just'), 1000);

lodashThrottled();
lodashThrottled();

justThrottled();
justThrottled();
```

</details>

You'll see that `just` gets printed once, but `lodash` is printed twice.

**Comment by ricardomatias** [comment]
As @WofWca mentions, just-throttle is broken. It doesn't always invoke the trailing call (the one that must happen).
