### ISSUE TITLE
Converting packages to named exports

### ISSUE THREAD

**Issue by PuruVJ** [angus-c/just#316]
Hi!

One thing I've noticed in this library is that some modules have default exports, some have named exports. This introduces some inconsistency, which I believe, we can get rid of.

Here's examples of some 
![image](https://user-images.githubusercontent.com/47742487/138582808-e3cabbff-5167-4c24-8803-1cad615e5494.png)

Here are 2 proposals from me:

1. Force all packages to be named export by default. This will introduce a major bump for almost every dependency
2. When #315 is merged, we'll have ES Modules, where we can add a named export along with the default export, reducing the breaking changes

ofc, it's a huge undertaking, and I don't expect you to do these chores yourself 😅. That's why I'll do whatever you suggest in a PR

What do you think?

**Comment by angus-c** [comment]
Both `diff` and `diff-apply` are named exports by design since those modules export multiple functions. All other modules use default exports and I would like to keep it that way for the reason Brandon mentioned. 

@PuruVJ I'm not sure where you are seeing `object-values` and `object-omit` having non default exports. Though, I might be missing something 🙂)

**Comment by PuruVJ** [comment]
Typescript definitions say these have nqmed exports.. Though it's fixed in latest releases when I pulled
