### ISSUE TITLE
just-partial-it implementation questions

### ISSUE THREAD

**Issue by camerow** [angus-c/just#6]
Hey, 

I got curious about the implementations you've got here - mostly for my own learning purposes. When I was playing with `just-partial-it` I had trouble understanding what role the`globalObj` has?

```
var globalObj = global || self;
globalObj.___ = {};
```

And taking that down through the code, what does this line do?

```
derivedArgs[i] = thisPartialArg === globalObj.___ ? arguments[argIndex++] : thisPartialArg;
```

It looks like it checks to see if `thisPartialArg === {}` which would always evaluate to false. 

Like I said, I just want to learn. =D

**Comment by angus-c** [comment]
Actually this is a great question.
When you invoke `partial` you need to pass placeholder arguments for this arguments you want to supply at runtime. In the following example we want to return a function that resolves the cubed root of something. That something is the placeholder indicated by _

```
import partial from 'just-partial-it';

const cubedRoot = partial(Math.pow, _, 1/3);
cubedRoot(10).toFixed(1); // 56.7
cubedRoot(35).toFixed(1); // 16.2
```

We need a way for the caller of partial to pass in an argument that will be recognized as a placeholder. One way to do this is to use a global variable. This is where `globalObj.___` comes in. 

Your question reveals a shortcoming in my example. We should first assign _ to `globalObj.___` before calling `partial`. (without this the function would likely throw an error since _ is probably undefined).

So for the example to work properly we need:

```
import partial from 'just-partial-it';

var _ = global.___;
const cubedRoot = partial(Math.pow, _, 1/3);
cubedRoot(10).toFixed(1); // 56.7
cubedRoot(35).toFixed(1); // 16.2
```

Which is annoying. I'm going to rewrite this to just use null as the placeholder which will mean we can remove all this global nonsense.

Thanks for bringing to my attention!

**Comment by craigbeck** [comment]
Actually using `_` (which is `undefined`) results in `NaN` as result from examples. Pull request #8 uses `undefined` as placeholder. `null` could be valid and useful value to pass, but `undefined` is clear, explict, and unambigous (i.e. `null` is value or placeholder?)

**Comment by camerow** [comment]
Craig stole my thunder. Get out of here Craig! (We work together...=D).

**Comment by angus-c** [comment]
@camerow feel free to find another bug :)
