### ISSUE TITLE
just-flip example code broken/doesn't work as expected?

### ISSUE THREAD

**Issue by vidhill** [angus-c/just#63]
I was looking at `just-flip`, 

I thought the example code looked interesting so I copied it into runkit, however the code does not git the expected result, an in the comments
It actually fails with an error, 

I tried to fix the example, but I couldn't quite work it out
something about the combination of `just-flip` and `just-map-object` 

```javascript
const flip = require('just-flip');
const map = require('just-map-object');
const curry = require('just-curry');

const numbers = {x: 5, y: 10};
const flippedMap = flip(map);
const double = curry(flippedMap, (_, number) => number * 2);
double(numbers) // {x: 10, y: 20];
```

https://runkit.com/vidhill/59e13d4ae9c3a00012eb22a8

**Comment by angus-c** [comment]
Hi, so I think the issue is just-curry doesn't work that way. It only takes the function as an argument, then saves subsequent args until it has enough.

```js
function add(a, b, c) {
  return a + b + c;
}
curry(add)(1)(2)(3);
```

You want just-partial instead (note it uses `undefined` and not `_` for the placeholder)

```js
const flip = require('just-flip');
const map = require('just-map-object');
const partial = require('just-partial-it');

const numbers = {x: 5, y: 10};
const flippedMap = flip(map);
const double = partial(flippedMap, (undefined, number) => number * 2);
double(numbers) // {x: 10, y: 20]
```
Here's the runkit...
https://runkit.com/angus-c/59e165c5dc90a9001269a7f4

Hope this helps.

**Comment by vidhill** [comment]
Cheers, 
Love the repo (utility set) by the way.
