### ISSUE TITLE
just-diff problem with dates

### ISSUE THREAD

**Issue by ilearnio** [angus-c/just#87]
`just-diff` package doesn't seem to be working fine with dates. Check this out https://runkit.com/artnikpro/5a6600fdc7cb7100129978e2

**Comment by angus-c** [comment]
This happens when a value is an object but has no properties (e.g. a date or a regex). 

Need to:
1) extend `replace` condition to include `!obj1KeysLength || !obj2KeysLength` (or add another replace push immediately on entering getDiff if `!obj1KeysLength || !obj2KeysLength`
2) write tests for this

**Comment by angus-c** [comment]
Pushed fix. Will publish tonight

**Comment by ilearnio** [comment]
Awesome! Thanks! 👍

**Comment by angus-c** [comment]
Should be fixed in @2.1.1
