### ISSUE TITLE
just-clone does not clone non-standard objects (eg a Date)

### ISSUE THREAD

**Issue by bytesnz** [angus-c/just#89]
If there is a Date in the object being clone, its clone is an empty Object. I would expect it to be a clone of the Date. I have put an example on [runkit](https://runkit.com/bytesnz/5a7d910c9be79a00122fc8ed)

**Comment by angus-c** [comment]
Similar issue to https://github.com/angus-c/just/issues/87 (will also affect just-extend). 
Will fix tonight.

**Comment by angus-c** [comment]
Turns out this was already partially fixed in v2.0.0 (I had forgotten to publish it!)

The cloned object will now return a date but it's not a clone of the original date. Non-plain objects (functions, dates, regex etc) each require their own specialized clone method so for v2 tests I explicitly didn't expect cloning of these types (https://github.com/angus-c/just/blob/master/test/collection-clone/index.js#L29)

**Comment by angus-c** [comment]
Fixed, now clones dates and regexps (but not functions)
